### ISSUE TITLE
Is it possible to streamline the requests more?

### ISSUE THREAD

**Issue by AqilCont** [117/alpaca-trade-api-ts#4]
This looks a bit redundant and unnecessary. I suggest just returning the request itself, as it doesn't make a big difference and takes an unnecessary function away from the call stack:

![image](https://user-images.githubusercontent.com/32044067/86522683-ba815580-be2f-11ea-84ce-2cb2a133aba7.png)

**Comment by 117** [comment]
Agreed, gonna write up some changes to simplify this. Thanks for pointing out the redundancy.

**Comment by 117** [comment]
The client requests have been simplified in commit [93af83f96ebc053d643e5db10ed01a40b9800184](https://github.com/117/alpaca-trade-api-ts/commit/93af83f96ebc053d643e5db10ed01a40b9800184).
