### ISSUE TITLE
Unnecessary `reconnect` options.

### ISSUE THREAD

**Issue by AqilCont** [117/alpaca-trade-api-ts#7]
I am very sure these options only add clutter to the class. Anyone can just put a listener on the `close` event and just re-initialize anyways, so there is literally no point. I would like to see a use case if otherwise.

**Comment by AqilCont** [comment]
I'm getting rid of this completely from the `Streams` API.

**Comment by 117** [comment]
Im all for passing reconnection onto the client user.

**Comment by AqilCont** [comment]
what do you mean?

**Comment by AqilCont** [comment]
Sorry, i was cleaning up the stream class xd

**Comment by AqilCont** [comment]
so uh, big mistake of me forgetting authentication. 
![image](https://user-images.githubusercontent.com/32044067/86543360-b74b9f80-beeb-11ea-8178-95b84f45a445.png)
I'm trying to figure out how to fix.

**Comment by 117** [comment]
Sorry again that im not able to merge or review these yet. On a long drive today.

**Comment by AqilCont** [comment]
Ohhhh, thats kewl. Have fun :D

**Comment by AqilCont** [comment]
I don't even know if you'll be able to use this but I started the documentation kind of.

**Comment by AqilCont** [comment]
![image](https://user-images.githubusercontent.com/32044067/86543383-f0840f80-beeb-11ea-9c7f-3eda6f67840a.png)

**Comment by AqilCont** [comment]
I think this deserves a big version called `0.2.0` if you *do* use any of this.

**Comment by AqilCont** [comment]
I don't even know why I am working so much on this, but part of it's definitely that I will have to use this in the future to make bots and I would rather have it be extremely smooth and user-friendly.

**Comment by AqilCont** [comment]
@117 How did you authenticate users before?

**Comment by 117** [comment]
Sends an ‘authentication’ message to the websocket server with key and secret.

**Comment by AqilCont** [comment]
How did you get it before? I didn't spot any Client parameter or key option.

**Comment by AqilCont** [comment]
Sorry for the late response, I took a shower and did some chores xd

**Comment by 117** [comment]
> How did you get it before? I didn't spot any Client parameter or key option.

The client is passed in the Stream constructor.

**Comment by AqilCont** [comment]
oh

**Comment by AqilCont** [comment]
I don't get why this error is happening: 
![image](https://user-images.githubusercontent.com/32044067/86552108-0659fa80-bf15-11ea-841d-061bbb52a4bc.png)
Do you happen to have any clue?

**Comment by AqilCont** [comment]
Ok, fixed it... everything should be done now :D

**Comment by AqilCont** [comment]
Fixed in a new commit, so this should be closed.
